# Configuration for Label Actions - https://github.com/dessant/label-actions

# Specify actions for issues and pull requests
actions:
  # Actions taken when the `repro-required` label is added
  repro-required:
    # Post a comment
    comment: >
      :wave: @{issue-author}, sorry you're having an issue. This issue is being closed because it does not provide all information required by the [issue template](https://raw.githubusercontent.com/react-native-datetimepicker/.github/master/.github/ISSUE_TEMPLATE/bug_report.md).
      
      As the issue template explains, we require that you provide a runnable example that reproduces your issue and your environment information.
      This means you need to provide a git repository with code that reproduces the issue.

      The reason is that maintainers do not have time to try reproduce bugs themselves. Please try to minimize the superfluous code and focus only on reproducing the bug.

      Please create a new issue with this and we'll be happy to review it!
    # Lock the thread
    lock: true
    close: true
  # Actions taken when the `repro-required` label is removed
  -repro-required:
    # Unlock the thread
    unlock: true
    open: true

# Limit to only `issues` or `pulls`
# only: issues

# Repository to extend settings from
# _extends: repo
