name: "\U0001F41B Bug Report"
description: 'Report a bug'
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this entire form.
  - type: checkboxes
    attributes:
      label: I have searched open and closed issues for this issue.
      options:
        - label: I have searched open and closed issues.
          required: true
  - type: checkboxes
    attributes:
      label: I have read and understood the license (link below).
      options:
        - label: I have read and understood the [license](https://github.com/react-native-documents/document-picker/blob/main/LICENSE.md).
          required: true
  - type: input
    attributes:
      label: Minimal reproducible example
      description: |
        A link to a GitHub repository containing a minimal reproducible example. This repository should include as little code as possible and not include extraneous dependencies.

        Try to reproduce the bugs on the provided example app. Either provide a link to the repo that reproduces the bug or provide your version of the `App.tsx` file that reproduces the issue and that we can easily use.

        If a reproducible example is not provided, your issue is likely to be closed.
        [Learn more about creating a minimal reproducible example](https://stackoverflow.com/help/mcve).
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What platform(s) does this occur on?
      multiple: true
      options:
        - Android
        - iOS
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Did you reproduce on a real device or emulator / simulator?
      multiple: false
      options:
        - Select an option
        - real device
        - emulator / simulator
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Explain the steps we need to take to reproduce the issue. Include a video or screenshots if you think it may help.
        Clearly describe what the expected behavior is and what instead is actually happening. Be concise and precise in your description.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: If the issue is related to specific file(s), I have linked the files so that others can reproduce exactly what I see.
      options:
        - label: I have attached files necessary to reproduce the problem (if applicable).
          required: true
  - type: textarea
    attributes:
      label: Stacktrace of the crash (if applicable)
      render: shell
      description: |
        Give the stacktrace of the crash, or explain the error message you are seeing. This will be automatically formatted into code.
    validations:
      required: true
  - type: textarea
    attributes:
      render: text
      label: Your computer environment
      description: Run the `npx react-native info` command and paste its output in the field below.
    validations:
      required: true
