name: Android build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/android.yml'
      - 'packages/**/android**'
  pull_request:
    paths:
      - '.github/workflows/android.yml'
      - 'packages/**/android/**'

jobs:
  android-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [old, new]
        include:
          - arch: old
            new-arch-enabled: false
            description: "old architecture"
          - arch: new
            new-arch-enabled: true
            description: "new architecture"
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Use Node.js lts
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build android example app on ${{ matrix.description }}
        run: ./gradlew app:assembleDebug -PnewArchEnabled=${{ matrix.new-arch-enabled }}
        working-directory: example/android
