name: Android build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/android.yml'
      - 'packages/**/android**'
  pull_request:
    paths:
      - '.github/workflows/android.yml'
      - 'packages/**/android/**'

jobs:
  android-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [old, new]
        include:
          - arch: old
            new-arch-enabled: false
            description: "old architecture"
          - arch: new
            new-arch-enabled: true
            description: "new architecture"
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build android example app on ${{ matrix.description }}
        run: ./gradlew app:assembleDebug -PnewArchEnabled=${{ matrix.new-arch-enabled }}
        working-directory: example/android
