name: iOS build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ios.yml'
      - 'packages/**/ios**'
      - 'packages/**/*.podspec'
  pull_request:
    paths:
      - '.github/workflows/ios.yml'
      - 'packages/**/ios**'
      - 'packages/**/*.podspec'

jobs:
  ios-build:
    runs-on: macos-26
    strategy:
      matrix:
        arch: [old, new]
        include:
          - arch: old
            new-arch-enabled: 0
            description: "old architecture"
          - arch: new
            new-arch-enabled: 1
            description: "new architecture"
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          working-directory: example/ios
          bundler-cache: true
      - name: Install dependencies
        run: yarn install --immutable
      - name: Install pods
        run: RCT_NEW_ARCH_ENABLED=${{ matrix.new-arch-enabled }} RCT_USE_PREBUILT_RNCORE=1 RCT_USE_RN_DEP=1 npx pod-install
        working-directory: example/ios
      - name: Build ios example app on ${{ matrix.description }}
        run: xcodebuild -scheme ReactTestApp -workspace document-picker-example.xcworkspace ONLY_ACTIVE_ARCH=NO -sdk iphonesimulator -configuration Debug
        working-directory: example/ios
